export const GENRES = [
  { id: 'action', label: 'Action', emoji: '⚔️', count: '1.2k mangas' },
  { id: 'aventure', label: 'Aventure', emoji: '🏃', count: '1.0k mangas' },
  { id: 'comedie', label: 'Comédie', emoji: '😂', count: '1.1k mangas' },
  { id: 'drame', label: 'Drame', emoji: '🎭', count: '860 mangas' },
  {id: 'ecchi', label: 'Ecchi', emoji: '😈', count: '450 mangas' },
  { id: 'fantasy', label: 'Fantastique', emoji: '🔮', count: '740 mangas' },
  { id: 'historique', label: 'Historique', emoji: '🏰', count: '360 mangas' },
  { id: 'horreur', label: 'Horreur', emoji: '😱', count: '420 mangas' },
  {id: 'mahoushoujo', label: 'Mahou Shoujo', emoji: '🪄', count: '150 mangas' },
  {id: 'mecha', label: 'Mecha', emoji: '🤖', count: '270 mangas'},
  {id:'music', label: 'Musique', emoji: '🎵', count: '200 mangas'},
  {id: 'mystere', label: 'Mystère', emoji: '🕵️', count: '330 mangas' },
  {id:'psychologique', label: 'Psychologique', emoji: '🧠', count: '290 mangas'},
  { id: 'romance', label: 'Romance', emoji: '💕', count: '980 mangas' },
  { id: 'scifi', label: 'Science-Fiction', emoji: '🤖', count: '530 mangas' },
  {id: 'sliceoflife', label: 'Tranche de vie', emoji: '🏠', count: '610 mangas'},
  {id:'sports', label: 'Sports', emoji: '🏅', count: '400 mangas'},
  {id:'supernatural', label: 'Surnaturel', emoji: '👻', count: '620 mangas'},
  { id: 'seinen', label: 'Seinen', emoji: '🎓', count: '310 mangas' },
  { id: 'shojo', label: 'Shojo', emoji: '🌸', count: '290 mangas' },
  { id: 'shonen', label: 'Shonen', emoji: '💪', count: '1.4k mangas' },
  { id: 'thriller', label: 'Thriller', emoji: '🔪', count: '380 mangas' },
];
